### ISSUE TITLE
Difference between regular and paranoid mode

### ISSUE THREAD

**Issue by DVassilev** [8go/TrezorSymmetricFileEncryption#5]
Could you just clarify what the difference is between regular and paranoid mode? Is the need for paranoid mode the case where you don't trust the computer to hold the key for encryption?

**Comment by 8go** [comment]
Correct. 

In the regular mode, the cryptographic key resides in the memory of the PC for a short amount of time. Imagine, your PC is infected by a virus that has full control over your PC but has only a low bandwidth back to the hacker. Now imagine you are encrypting a 10M file in regular mode. The virus might not be fast enough or not have sufficient bandwidth to transfer the plain-text 10M file back to the hacker. But the virus might have enough bandwidth to steal the key from memory and send the tiny key back to the hacker. If the hacker at some future point in time gets access to your encrypted file (e.g. because you thought it is safe to store on DropBox) it can decrypt it. 

Now, in paranoid mode, the above scenario is impossible. The hacker or virus will not be able to decrypt the encrypted file because it is encrypted twice and the second key never left the Trezor and can hence not be stolen. The cost is that the operation is very slow, i.e. time consuming.

It depends on the scenario, but if possible, a truly paranoid person would perform the operations on an offline air-gapped computer.

**Comment by Xxxxffjtkkskkkernnr** [comment]
Difference between regular and paranoid mode #5
@DVassilev
DVassilev opened this issue 
about 1 year ago
